server:
  port: 8123
  servlet:
    context-path: /api
    #cookie 30天过期
    session:
      cookie:
        max-age: 259200
spring:
  application:
    name: yuan-picture-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yuan_picture
    username: root
    password: 123456
  #Redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    connect-timeout: 5000
  #Session 配置
  session:
    store-type: redis
    timeout: 259200
  servlet:
    multipart:
      max-file-size: 10MB
    # 空间图片分表
  shardingsphere:
    datasource:
      names: yuan_picture
      yuan_picture:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/yuan_picture
        username: root
        password: 123456
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: yuan_picture.picture   # 动态分表
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.yuanc.yuanpicturebackend.manager.sharding.PictureShardingAlgorithm
    props:
      sql-show: true

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    #仅仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
    enable-sql-runner: true
knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yuanc.yuanpicturebackend.controller

# 阿里云 AI 配置
aliYunAi:
  apiKey: sk-d7e41b277abd4ca198e58eb746ff8e7e
